apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gocuts.fullname" . }}-config
  labels:
    {{- include "gocuts.labels" . | nindent 4 }}
data:
  gocuts.toml: |
    {{- .Values.config.toml | nindent 4 }}