{{- if .Values.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gocuts.fullname" . }}
  labels:
    {{- include "gocuts.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.key | quote }}
{{- end }}